// Code generated by ent, DO NOT EDIT.

package ent

import (
	"IM/internel/db/ent/friendapply"
	"IM/internel/db/ent/predicate"
	"IM/internel/db/ent/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FriendApplyQuery is the builder for querying FriendApply entities.
type FriendApplyQuery struct {
	config
	ctx          *QueryContext
	order        []friendapply.OrderOption
	inters       []Interceptor
	predicates   []predicate.FriendApply
	withFromUser *UserQuery
	withToUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FriendApplyQuery builder.
func (faq *FriendApplyQuery) Where(ps ...predicate.FriendApply) *FriendApplyQuery {
	faq.predicates = append(faq.predicates, ps...)
	return faq
}

// Limit the number of records to be returned by this query.
func (faq *FriendApplyQuery) Limit(limit int) *FriendApplyQuery {
	faq.ctx.Limit = &limit
	return faq
}

// Offset to start from.
func (faq *FriendApplyQuery) Offset(offset int) *FriendApplyQuery {
	faq.ctx.Offset = &offset
	return faq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (faq *FriendApplyQuery) Unique(unique bool) *FriendApplyQuery {
	faq.ctx.Unique = &unique
	return faq
}

// Order specifies how the records should be ordered.
func (faq *FriendApplyQuery) Order(o ...friendapply.OrderOption) *FriendApplyQuery {
	faq.order = append(faq.order, o...)
	return faq
}

// QueryFromUser chains the current query on the "from_user" edge.
func (faq *FriendApplyQuery) QueryFromUser() *UserQuery {
	query := (&UserClient{config: faq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := faq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := faq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(friendapply.Table, friendapply.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, friendapply.FromUserTable, friendapply.FromUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(faq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryToUser chains the current query on the "to_user" edge.
func (faq *FriendApplyQuery) QueryToUser() *UserQuery {
	query := (&UserClient{config: faq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := faq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := faq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(friendapply.Table, friendapply.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, friendapply.ToUserTable, friendapply.ToUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(faq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FriendApply entity from the query.
// Returns a *NotFoundError when no FriendApply was found.
func (faq *FriendApplyQuery) First(ctx context.Context) (*FriendApply, error) {
	nodes, err := faq.Limit(1).All(setContextOp(ctx, faq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{friendapply.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (faq *FriendApplyQuery) FirstX(ctx context.Context) *FriendApply {
	node, err := faq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FriendApply ID from the query.
// Returns a *NotFoundError when no FriendApply ID was found.
func (faq *FriendApplyQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = faq.Limit(1).IDs(setContextOp(ctx, faq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{friendapply.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (faq *FriendApplyQuery) FirstIDX(ctx context.Context) int64 {
	id, err := faq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FriendApply entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FriendApply entity is found.
// Returns a *NotFoundError when no FriendApply entities are found.
func (faq *FriendApplyQuery) Only(ctx context.Context) (*FriendApply, error) {
	nodes, err := faq.Limit(2).All(setContextOp(ctx, faq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{friendapply.Label}
	default:
		return nil, &NotSingularError{friendapply.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (faq *FriendApplyQuery) OnlyX(ctx context.Context) *FriendApply {
	node, err := faq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FriendApply ID in the query.
// Returns a *NotSingularError when more than one FriendApply ID is found.
// Returns a *NotFoundError when no entities are found.
func (faq *FriendApplyQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = faq.Limit(2).IDs(setContextOp(ctx, faq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{friendapply.Label}
	default:
		err = &NotSingularError{friendapply.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (faq *FriendApplyQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := faq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FriendApplies.
func (faq *FriendApplyQuery) All(ctx context.Context) ([]*FriendApply, error) {
	ctx = setContextOp(ctx, faq.ctx, "All")
	if err := faq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FriendApply, *FriendApplyQuery]()
	return withInterceptors[[]*FriendApply](ctx, faq, qr, faq.inters)
}

// AllX is like All, but panics if an error occurs.
func (faq *FriendApplyQuery) AllX(ctx context.Context) []*FriendApply {
	nodes, err := faq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FriendApply IDs.
func (faq *FriendApplyQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if faq.ctx.Unique == nil && faq.path != nil {
		faq.Unique(true)
	}
	ctx = setContextOp(ctx, faq.ctx, "IDs")
	if err = faq.Select(friendapply.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (faq *FriendApplyQuery) IDsX(ctx context.Context) []int64 {
	ids, err := faq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (faq *FriendApplyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, faq.ctx, "Count")
	if err := faq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, faq, querierCount[*FriendApplyQuery](), faq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (faq *FriendApplyQuery) CountX(ctx context.Context) int {
	count, err := faq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (faq *FriendApplyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, faq.ctx, "Exist")
	switch _, err := faq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (faq *FriendApplyQuery) ExistX(ctx context.Context) bool {
	exist, err := faq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FriendApplyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (faq *FriendApplyQuery) Clone() *FriendApplyQuery {
	if faq == nil {
		return nil
	}
	return &FriendApplyQuery{
		config:       faq.config,
		ctx:          faq.ctx.Clone(),
		order:        append([]friendapply.OrderOption{}, faq.order...),
		inters:       append([]Interceptor{}, faq.inters...),
		predicates:   append([]predicate.FriendApply{}, faq.predicates...),
		withFromUser: faq.withFromUser.Clone(),
		withToUser:   faq.withToUser.Clone(),
		// clone intermediate query.
		sql:  faq.sql.Clone(),
		path: faq.path,
	}
}

// WithFromUser tells the query-builder to eager-load the nodes that are connected to
// the "from_user" edge. The optional arguments are used to configure the query builder of the edge.
func (faq *FriendApplyQuery) WithFromUser(opts ...func(*UserQuery)) *FriendApplyQuery {
	query := (&UserClient{config: faq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	faq.withFromUser = query
	return faq
}

// WithToUser tells the query-builder to eager-load the nodes that are connected to
// the "to_user" edge. The optional arguments are used to configure the query builder of the edge.
func (faq *FriendApplyQuery) WithToUser(opts ...func(*UserQuery)) *FriendApplyQuery {
	query := (&UserClient{config: faq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	faq.withToUser = query
	return faq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FriendApply.Query().
//		GroupBy(friendapply.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (faq *FriendApplyQuery) GroupBy(field string, fields ...string) *FriendApplyGroupBy {
	faq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FriendApplyGroupBy{build: faq}
	grbuild.flds = &faq.ctx.Fields
	grbuild.label = friendapply.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at"`
//	}
//
//	client.FriendApply.Query().
//		Select(friendapply.FieldCreatedAt).
//		Scan(ctx, &v)
func (faq *FriendApplyQuery) Select(fields ...string) *FriendApplySelect {
	faq.ctx.Fields = append(faq.ctx.Fields, fields...)
	sbuild := &FriendApplySelect{FriendApplyQuery: faq}
	sbuild.label = friendapply.Label
	sbuild.flds, sbuild.scan = &faq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FriendApplySelect configured with the given aggregations.
func (faq *FriendApplyQuery) Aggregate(fns ...AggregateFunc) *FriendApplySelect {
	return faq.Select().Aggregate(fns...)
}

func (faq *FriendApplyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range faq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, faq); err != nil {
				return err
			}
		}
	}
	for _, f := range faq.ctx.Fields {
		if !friendapply.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if faq.path != nil {
		prev, err := faq.path(ctx)
		if err != nil {
			return err
		}
		faq.sql = prev
	}
	return nil
}

func (faq *FriendApplyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FriendApply, error) {
	var (
		nodes       = []*FriendApply{}
		_spec       = faq.querySpec()
		loadedTypes = [2]bool{
			faq.withFromUser != nil,
			faq.withToUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FriendApply).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FriendApply{config: faq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, faq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := faq.withFromUser; query != nil {
		if err := faq.loadFromUser(ctx, query, nodes, nil,
			func(n *FriendApply, e *User) { n.Edges.FromUser = e }); err != nil {
			return nil, err
		}
	}
	if query := faq.withToUser; query != nil {
		if err := faq.loadToUser(ctx, query, nodes, nil,
			func(n *FriendApply, e *User) { n.Edges.ToUser = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (faq *FriendApplyQuery) loadFromUser(ctx context.Context, query *UserQuery, nodes []*FriendApply, init func(*FriendApply), assign func(*FriendApply, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*FriendApply)
	for i := range nodes {
		fk := nodes[i].FromUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "from_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (faq *FriendApplyQuery) loadToUser(ctx context.Context, query *UserQuery, nodes []*FriendApply, init func(*FriendApply), assign func(*FriendApply, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*FriendApply)
	for i := range nodes {
		fk := nodes[i].ToUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "to_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (faq *FriendApplyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := faq.querySpec()
	_spec.Node.Columns = faq.ctx.Fields
	if len(faq.ctx.Fields) > 0 {
		_spec.Unique = faq.ctx.Unique != nil && *faq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, faq.driver, _spec)
}

func (faq *FriendApplyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(friendapply.Table, friendapply.Columns, sqlgraph.NewFieldSpec(friendapply.FieldID, field.TypeInt64))
	_spec.From = faq.sql
	if unique := faq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if faq.path != nil {
		_spec.Unique = true
	}
	if fields := faq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, friendapply.FieldID)
		for i := range fields {
			if fields[i] != friendapply.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if faq.withFromUser != nil {
			_spec.Node.AddColumnOnce(friendapply.FieldFromUserID)
		}
		if faq.withToUser != nil {
			_spec.Node.AddColumnOnce(friendapply.FieldToUserID)
		}
	}
	if ps := faq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := faq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := faq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := faq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (faq *FriendApplyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(faq.driver.Dialect())
	t1 := builder.Table(friendapply.Table)
	columns := faq.ctx.Fields
	if len(columns) == 0 {
		columns = friendapply.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if faq.sql != nil {
		selector = faq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if faq.ctx.Unique != nil && *faq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range faq.predicates {
		p(selector)
	}
	for _, p := range faq.order {
		p(selector)
	}
	if offset := faq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := faq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FriendApplyGroupBy is the group-by builder for FriendApply entities.
type FriendApplyGroupBy struct {
	selector
	build *FriendApplyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fagb *FriendApplyGroupBy) Aggregate(fns ...AggregateFunc) *FriendApplyGroupBy {
	fagb.fns = append(fagb.fns, fns...)
	return fagb
}

// Scan applies the selector query and scans the result into the given value.
func (fagb *FriendApplyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fagb.build.ctx, "GroupBy")
	if err := fagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FriendApplyQuery, *FriendApplyGroupBy](ctx, fagb.build, fagb, fagb.build.inters, v)
}

func (fagb *FriendApplyGroupBy) sqlScan(ctx context.Context, root *FriendApplyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fagb.fns))
	for _, fn := range fagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fagb.flds)+len(fagb.fns))
		for _, f := range *fagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FriendApplySelect is the builder for selecting fields of FriendApply entities.
type FriendApplySelect struct {
	*FriendApplyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fas *FriendApplySelect) Aggregate(fns ...AggregateFunc) *FriendApplySelect {
	fas.fns = append(fas.fns, fns...)
	return fas
}

// Scan applies the selector query and scans the result into the given value.
func (fas *FriendApplySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fas.ctx, "Select")
	if err := fas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FriendApplyQuery, *FriendApplySelect](ctx, fas.FriendApplyQuery, fas, fas.inters, v)
}

func (fas *FriendApplySelect) sqlScan(ctx context.Context, root *FriendApplyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fas.fns))
	for _, fn := range fas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
